export const END_POINT = "http://localhost:3000";

export const CHAMPS = {
  GET: "GET_CHAMP",
  GET_CHAMPS_SUCCESS: "GET_CHAMPS_SUCCESS",
  GET_CHAMPS_FAILED: "GET_CHAMPS_FAILED"
}

export const MATCHES = {
  GET: "GET_MATCHES",
  GET_MATCHES_SUCCESS: "GET_MATCHES_SUCCESS",
  GET_MATCHES_FAILED: "GET_MATCHES_FAILED"
}
export const LEAGUES = {
  GET: "GET_LEAGUE",
  GET_LEAGUES_SUCCESS: "GET_LEAGUES_SUCCESS",
  GET_LEAGUES_FAILED: "GET_LEAGUES_FAILED",
  GET_RANKING_SUCCESS: "GET_RANKING_SUCCESS",
  GET_RANKING_FAILED: "GET_RANKING_FAILED",
  SET_SELECTED_LEAGUE: "SET_SELECTED_LEAGUE"

}

export const ALL_LEAGUES = {
  GET: "GET_ALL_LEAGUES",
  GET_ALL_LEAGUES_SUCCESS: "GET_ALL_LEAGUES_SUCCESS",
  GET_ALL_LEAGUES_FAILED: "GET_ALL_LEAGUES_FAILED",
  CLEAR_LEAGUE: "CLEAR_LEAGUE"
}

export const TEST = "TEST"
export const TEST_SUCCESS = "TEST_SUCCESS"
export const TEST_FAIL = "TEST_FAIL"

export const COUNTRIES = {
  GET: "GET_COUNTRY",
  GET_COUNTRY_SUCCESS: "GET_COUNTRY_SUCCESS",
  GET_COUNTRY_FAILED: "GET_COUNTRY_FAILED",
  GET_COUNTRY_SELECTED: "GET_COUNTRY_SELECTED"
}
export const SQUAD = {
  GET: "GET_SQUAD",
  GET_SQUAD_SUCCESS: "GET_SQUAD_SUCCESS",
  GET_SQUAD_FAILED: "GET_SQUAD_FAILED"
}

export const TEAMS = {
  GET_TEAMS_SUCCESS: "GET_TEAMS_SUCCESS",
  GET_TEAMS_FAILED: "GET_TEAMS_FAILED",
  SET_TEAMS_BY_LEAGUE: "SET_TEAMS_BY_LEAGUE",
  GET_TEAM_BY_ID_SUCCESS: "GET_TEAM_BY_ID_SUCCESS",
  GET_TEAM_BY_ID_FAILED: "GET_TEAM_BY_ID_FAILED",
  SET_TEAM_SELECTED: "SET_TEAM_SELECTED",
  GET_TEAM_TRANSFERS_SUCCESS: "GET_TEAM_TRANSFERS_SUCCESS",
  GET_TEAM_TRANSFERS_FAILED: "GET_TEAM_TRANSFERS_FAILED"
}

export const LOGO = {
  LEAGUE: "https://upload.wikimedia.org/wikipedia/fr/thumb/4/43/Logo_Olympique_de_Marseille.svg/806px-Logo_Olympique_de_Marseille.svg.png",
  TEAM: "http://www.barbadosfa.com/images/team-placeholder-logo.e50b9536.png"
}